name: performance tracking
env:
  JULIA_NUM_THREADS: 2
on:
  pull_request:
    branches:
      - master
      - benchexp
  push:
    branches:
      - master
      - benchexp
    tags: '*'
jobs:
  benchmark:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        version:
          # - 'nightly'
          - '1'
          # - '1.6'
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        arch:
          - x64
        include:
          # - version: 'nightly'
          #   allow_failure: true
          - version: '1'
            allow_failure: false
          # - version: '1.6'
            # allow_failure: false
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - name: install dependencies
        run: julia -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI@0.1"'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Deduct baseline and run benchmark judge
        env:
          BASELINE: ${{ (github.event_name == 'pull_request') && github.base_ref || github.ref_name }}
        run: julia -e "using BenchmarkCI, PkgBenchmark; 
          jd=BenchmarkCI.judge(baseline=\"origin/${{ env.BASELINE }}\"); 
          @show(jd.target_results);
          @show(jd.baseline_results);
          writeresults(\"benchout.json\", jd.target_results); 
          jd"
      - name: Post results if pull request
        if: github.event_name == 'pull_request'
        run: julia -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push results if push/merge
        if: github.event_name == 'push'
        run: julia -e "using BenchmarkCI; BenchmarkCI.pushresult(; url=\"git@github.com:filchristou/Graphs.jl-benchmarks-results-test.git\", branch=\"${GITHUB_REF_NAME}\")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.DATA_SSH_KEY }}
      - uses: actions/upload-artifact@v3
        with: 
          name: Store benchmark result
          path: benchout.json

